version: "3.3"

services:
  pugmaster:
    build: .
    container_name: pugmaster
    restart: "always"
    networks:
      - "proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pugmaster.rule=Host(`pugmaster.challenge.sict-ccs.club`)"
      - "traefik.http.routers.pugmaster.entrypoints=web"

networks:
  proxy:
    external:
      name: "traefik_proxy"
